(eval-when (:load-toplevel :compile-toplevel)
  (identity #.(load "~/quicklisp/setup"))
  (identity #.(push (make-pathname 
                     :directory '(:relative "verrazano")
                     :name nil
                     :type nil
                     :defaults (or *load-truename* *compile-file-truename*)) ql:*local-project-directories*))
  (identity #.(ql:quickload :verrazano)))

(defpackage :bullet-cffi-wrap
  (:use :cl :alexandria :split-sequence :verrazano))
(in-package :bullet-cffi-wrap)

(generate-binding 
 (list :cffi 
       :package-name :bullet-cffi 
       :output-filename #p"/tmp/bullet-cffi.lisp"
       :input-files (list "BulletDynamics/Dynamics/btRigidBody.h" 
                          "BulletDynamics/Dynamics/btActionInterface.h" 
                          "BulletDynamics/Dynamics/btDynamicsWorld.h" 
                          "BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h" 
                          "BulletDynamics/Dynamics/btSimpleDynamicsWorld.h" 
                          "BulletDynamics/ConstraintSolver/btHingeConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btSolverConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btHinge2Constraint.h" 
                          "BulletDynamics/ConstraintSolver/btJacobianEntry.h" 
                          "BulletDynamics/ConstraintSolver/btFixedConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btConstraintSolver.h" 
                          "BulletDynamics/ConstraintSolver/btGearConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btContactSolverInfo.h" 
                          "BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btSliderConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btUniversalConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h" 
                          "BulletDynamics/ConstraintSolver/btTypedConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btSolverBody.h" 
                          "BulletDynamics/ConstraintSolver/btContactConstraint.h" 
                          "BulletDynamics/ConstraintSolver/btConeTwistConstraint.h" 
                          "BulletDynamics/Character/btKinematicCharacterController.h" 
                          "BulletDynamics/Character/btCharacterControllerInterface.h" 
                          "BulletDynamics/Vehicle/btVehicleRaycaster.h" 
                          "BulletDynamics/Vehicle/btWheelInfo.h" 
                          "BulletDynamics/Vehicle/btRaycastVehicle.h" 
                          "BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h" 
                          "BulletDynamics/Featherstone/btMultiBodyConstraint.h" 
                          "BulletDynamics/Featherstone/btMultiBody.h" 
                          "BulletDynamics/Featherstone/btMultiBodyLinkCollider.h" 
                          "BulletDynamics/Featherstone/btMultiBodyLink.h" 
                          "BulletDynamics/Featherstone/btMultiBodySolverConstraint.h" 
                          "BulletDynamics/Featherstone/btMultiBodyPoint2Point.h" 
                          "BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h" 
                          "LinearMath/btQuaternion.h" 
                          "LinearMath/btQuickprof.h" 
                          "LinearMath/btDefaultMotionState.h" 
                          "LinearMath/btQuadWord.h" 
                          "LinearMath/btConvexHull.h" 
                          "LinearMath/btPoolAllocator.h" 
                          "LinearMath/btPolarDecomposition.h" 
                          "LinearMath/btScalar.h" 
                          "LinearMath/btMinMax.h" 
                          "LinearMath/btAlignedAllocator.h" 
                          "LinearMath/btRandom.h" 
                          "LinearMath/btGeometryUtil.h" 
                          "LinearMath/btHashMap.h" 
                          "LinearMath/btIDebugDraw.h" 
                          "LinearMath/btTransform.h" 
                          "LinearMath/btAlignedObjectArray.h" 
                          "LinearMath/btVector3.h" 
                          "LinearMath/btList.h" 
                          "LinearMath/btTransformUtil.h" 
                          "LinearMath/btMotionState.h" 
                          "LinearMath/btStackAlloc.h" 
                          "LinearMath/btMatrix3x3.h" 
                          "LinearMath/btSerializer.h" 
                          "LinearMath/btAabbUtil2.h" 
                          "btBulletCollisionCommon.h" 
                          "btBulletDynamicsCommon.h" 
                          "Bullet-C-Api.h" 
                          "BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h" 
                          "BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h" 
                          "BulletCollision/NarrowPhaseCollision/btRaycastCallback.h" 
                          "BulletCollision/NarrowPhaseCollision/btManifoldPoint.h" 
                          "BulletCollision/NarrowPhaseCollision/btPointCollector.h" 
                          "BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h" 
                          "BulletCollision/NarrowPhaseCollision/btConvexCast.h" 
                          "BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h" 
                          "BulletCollision/NarrowPhaseCollision/btPersistentManifold.h" 
                          "BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h" 
                          "BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h" 
                          "BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h" 
                          "BulletCollision/NarrowPhaseCollision/btGjkEpa2.h" 
                          "BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h" 
                          "BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h" 
                          "BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h" 
                          "BulletCollision/BroadphaseCollision/btAxisSweep3.h" 
                          "BulletCollision/BroadphaseCollision/btBroadphaseProxy.h" 
                          "BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h" 
                          "BulletCollision/BroadphaseCollision/btQuantizedBvh.h" 
                          "BulletCollision/BroadphaseCollision/btDbvt.h" 
                          "BulletCollision/BroadphaseCollision/btOverlappingPairCache.h" 
                          "BulletCollision/BroadphaseCollision/btMultiSapBroadphase.h" 
                          "BulletCollision/BroadphaseCollision/btDispatcher.h" 
                          "BulletCollision/BroadphaseCollision/btBroadphaseInterface.h" 
                          "BulletCollision/BroadphaseCollision/btSimpleBroadphase.h" 
                          "BulletCollision/BroadphaseCollision/btDbvtBroadphase.h" 
                          "BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h" 
                          "BulletCollision/CollisionShapes/btTetrahedronShape.h" 
                          "BulletCollision/CollisionShapes/btTriangleInfoMap.h" 
                          "BulletCollision/CollisionShapes/btMaterial.h" 
                          "BulletCollision/CollisionShapes/btCompoundShape.h" 
                          "BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h" 
                          "BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h" 
                          "BulletCollision/CollisionShapes/btOptimizedBvh.h" 
                          "BulletCollision/CollisionShapes/btUniformScalingShape.h" 
                          "BulletCollision/CollisionShapes/btMinkowskiSumShape.h" 
                          "BulletCollision/CollisionShapes/btTriangleShape.h" 
                          "BulletCollision/CollisionShapes/btConvexInternalShape.h" 
                          "BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h" 
                          "BulletCollision/CollisionShapes/btCylinderShape.h" 
                          "BulletCollision/CollisionShapes/btConvexShape.h" 
                          "BulletCollision/CollisionShapes/btShapeHull.h" 
                          "BulletCollision/CollisionShapes/btStridingMeshInterface.h" 
                          "BulletCollision/CollisionShapes/btSphereShape.h" 
                          "BulletCollision/CollisionShapes/btBoxShape.h" 
                          "BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h" 
                          "BulletCollision/CollisionShapes/btConvex2dShape.h" 
                          "BulletCollision/CollisionShapes/btCapsuleShape.h" 
                          "BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h" 
                          "BulletCollision/CollisionShapes/btConvexPointCloudShape.h" 
                          "BulletCollision/CollisionShapes/btTriangleCallback.h" 
                          "BulletCollision/CollisionShapes/btCollisionMargin.h" 
                          "BulletCollision/CollisionShapes/btTriangleMeshShape.h" 
                          "BulletCollision/CollisionShapes/btConcaveShape.h" 
                          "BulletCollision/CollisionShapes/btMultiSphereShape.h" 
                          "BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h" 
                          "BulletCollision/CollisionShapes/btPolyhedralConvexShape.h" 
                          "BulletCollision/CollisionShapes/btTriangleBuffer.h" 
                          "BulletCollision/CollisionShapes/btEmptyShape.h" 
                          "BulletCollision/CollisionShapes/btBox2dShape.h" 
                          "BulletCollision/CollisionShapes/btCollisionShape.h" 
                          "BulletCollision/CollisionShapes/btTriangleMesh.h" 
                          "BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h" 
                          "BulletCollision/CollisionShapes/btConvexHullShape.h" 
                          "BulletCollision/CollisionShapes/btStaticPlaneShape.h" 
                          "BulletCollision/CollisionShapes/btConeShape.h" 
                          "BulletCollision/CollisionDispatch/btCollisionConfiguration.h" 
                          "BulletCollision/CollisionDispatch/btManifoldResult.h" 
                          "BulletCollision/CollisionDispatch/btSimulationIslandManager.h" 
                          "BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h" 
                          "BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btUnionFind.h" 
                          "BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btCollisionObject.h" 
                          "BulletCollision/CollisionDispatch/btHashedSimplePairCache.h" 
                          "BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btBoxBoxDetector.h" 
                          "BulletCollision/CollisionDispatch/btGhostObject.h" 
                          "BulletCollision/CollisionDispatch/btInternalEdgeUtility.h" 
                          "BulletCollision/CollisionDispatch/SphereTriangleDetector.h" 
                          "BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btCollisionCreateFunc.h" 
                          "BulletCollision/CollisionDispatch/btCollisionDispatcher.h" 
                          "BulletCollision/CollisionDispatch/btCollisionWorld.h" 
                          "BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h" 
                          "BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h" 
                          "BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h" 
                          "BulletSoftBody/btSoftBody.h" 
                          "BulletSoftBody/btSoftRigidCollisionAlgorithm.h" 
                          "BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h" 
                          "BulletSoftBody/btSoftBodyHelpers.h" 
                          "BulletSoftBody/btSoftRigidDynamicsWorld.h" 
                          "BulletSoftBody/btSparseSDF.h" 
                          "BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h" 
                          "BulletSoftBody/btSoftSoftCollisionAlgorithm.h" 
                          "BulletSoftBody/btSoftBodyInternals.h")
       :gccxml-flags "--gccxml-compiler g++ -I/home/brpocock/Private/violet-volts/Romance-II/src/romans/lib/cl-bullet2l/bullet2/ld/include/bullet"))
